
SET SQL DIALECT 3; 

/* CREATE DATABASE 'WHMXDOKUMENT.FDB' PAGE_SIZE 8192 DEFAULT CHARACTER SET NONE; */


/*  Generators or sequences */
CREATE GENERATOR GEN_DOKUMENT_ID;
CREATE GENERATOR GEN_DOKUMENT_MS_ID;
CREATE GENERATOR GEN_DOKUMENT_WEB_ID;

COMMIT WORK;

/* Table: DOKUMENT, Owner: SYSDBA */
CREATE TABLE DOKUMENT (LNR INTEGER NOT NULL,
        LNR_DOKU INTEGER,
        DOKU_TYPE INTEGER,
        MEMO BLOB SUB_TYPE 0 SEGMENT SIZE 80,
        LNR_GK BIGINT,
        LNR_ADR BIGINT,
        RECHNR BIGINT,
PRIMARY KEY (LNR));

/* Table: DOKUMENT_MS, Owner: SYSDBA */
CREATE TABLE DOKUMENT_MS (LNR INTEGER NOT NULL,
        LNR_GK INTEGER,
        LNR_ADR INTEGER,
        MEMO BLOB SUB_TYPE 0 SEGMENT SIZE 80,
        DOKU_TYPE INTEGER,
PRIMARY KEY (LNR));

/* Table: DOKUMENT_WEB, Owner: SYSDBA */
CREATE TABLE DOKUMENT_WEB (LNR INTEGER NOT NULL,
        ADR_LNR INTEGER,
        GK_LNR INTEGER,
        MEMO BLOB SUB_TYPE 0 SEGMENT SIZE 80,
        LNR_DOKU INTEGER,
PRIMARY KEY (LNR));

/*  Index definitions for all user tables */
CREATE INDEX DOKUMENT_MS_LNR_GK ON DOKUMENT_MS (LNR_GK);
SET TERM ^ ;

/* Triggers only will work for SQL triggers */
CREATE TRIGGER DOKUMENT_BI FOR DOKUMENT 
ACTIVE BEFORE INSERT POSITION 0 
AS
BEGIN
  IF (NEW.LNR IS NULL) THEN
    NEW.LNR = GEN_ID(GEN_DOKUMENT_ID,1);
END ^

CREATE TRIGGER DOKUMENT_MS_BI FOR DOKUMENT_MS 
ACTIVE BEFORE INSERT POSITION 0 
AS
BEGIN
  IF (NEW.LNR IS NULL) THEN
    NEW.LNR = GEN_ID(GEN_DOKUMENT_MS_ID,1);
END ^

CREATE TRIGGER DOKUMENT_WEB_BI FOR DOKUMENT_WEB 
ACTIVE BEFORE INSERT POSITION 0 
AS
BEGIN
  IF (NEW.LNR IS NULL) THEN
    NEW.LNR = GEN_ID(GEN_DOKUMENT_WEB_ID,1);
END ^


SET TERM ; ^
COMMIT WORK;

/* Grant permissions for this database */
GRANT USAGE ON SEQUENCE GEN_DOKUMENT_ID TO PUBLIC;
GRANT USAGE ON SEQUENCE GEN_DOKUMENT_WEB_ID TO PUBLIC;
