
SET SQL DIALECT 3; 

/* CREATE DATABASE '/tmp/winhotel-extract/winhotel.fdb' PAGE_SIZE 8192 DEFAULT CHARACTER SET NONE; */


/*  Generators or sequences */
CREATE GENERATOR GEN_FM_PROT_ID;
CREATE GENERATOR GEN_FREIMELD_PREISLIST_ID;
CREATE GENERATOR GEN_FREIMELD_VAKANZ_ID;
CREATE GENERATOR GEN_HIS_PROT_ID;
CREATE GENERATOR GEN_TEMP_RATEBOARD_ID;

COMMIT WORK;

/* Table: FM_PROT, Owner: SYSDBA */
CREATE TABLE FM_PROT (LNR INTEGER NOT NULL,
        PROVIDER INTEGER,
        GESAMT INTEGER DEFAULT 0,
        TRANS INTEGER DEFAULT 0,
        FEHLER INTEGER DEFAULT 0,
        SEND INTEGER DEFAULT 0,
        EMPFANGEN INTEGER DEFAULT 0,
        DATUMZEIT TIMESTAMP DEFAULT current_timestamp,
        PROTOKOLL BLOB SUB_TYPE TEXT SEGMENT SIZE 8192,
PRIMARY KEY (LNR));

/* Table: FREIMELD_PREISLIST, Owner: SYSDBA */
CREATE TABLE FREIMELD_PREISLIST (LNR INTEGER NOT NULL,
        PROVIDER INTEGER,
        FM_RATEID VARCHAR(30),
        UEBTR_DATUM TIMESTAMP DEFAULT current_timestamp,
        VONDATUM DATE,
        BISDATUM DATE,
        MINSTAY INTEGER DEFAULT 0,
        MAXSTAY INTEGER DEFAULT 0,
        BETRAG NUMERIC(12, 2) DEFAULT 0,
        B1 NUMERIC(12, 2) DEFAULT 0,
        B2 NUMERIC(12, 2) DEFAULT 0,
        B3 NUMERIC(12, 2) DEFAULT 0,
        B4 NUMERIC(12, 2) DEFAULT 0,
        B5 NUMERIC(12, 2) DEFAULT 0,
        B6 NUMERIC(12, 2) DEFAULT 0,
        KATE_EXTERN VARCHAR(15),
PRIMARY KEY (LNR));

/* Table: FREIMELD_VAKANZ, Owner: SYSDBA */
CREATE TABLE FREIMELD_VAKANZ (LNR INTEGER NOT NULL,
        PROVIDER INTEGER,
        KATE_EXTERN VARCHAR(20),
        UEBTR_DATUM TIMESTAMP DEFAULT current_timestamp ,
        DATUM DATE,
        VERFUEGBAR INTEGER DEFAULT 0,
        MINSTAY INTEGER DEFAULT 0,
        MAXSTAY INTEGER DEFAULT 0,
        BETRAG NUMERIC(12, 2) DEFAULT 0,
PRIMARY KEY (LNR));

/* Table: HIS_PROT, Owner: SYSDBA */
CREATE TABLE HIS_PROT (LNR INTEGER NOT NULL,
        PROVIDER INTEGER,
        GESAMT INTEGER DEFAULT 0,
        TRANS INTEGER DEFAULT 0,
        FEHLER INTEGER DEFAULT 0,
        SEND INTEGER DEFAULT 0,
        EMPFANGEN INTEGER DEFAULT 0,
        DATUMZEIT TIMESTAMP DEFAULT current_timestamp,
        PROTOKOLL BLOB SUB_TYPE TEXT SEGMENT SIZE 8192,
PRIMARY KEY (LNR));

/* Table: TEMP_RATEBOARD, Owner: SYSDBA */
CREATE TABLE TEMP_RATEBOARD (LNR INTEGER NOT NULL,
        GK_LNR INTEGER,
        DATUM DATE,
        BETRAG NUMERIC(12, 2) DEFAULT 0,
        ERW INTEGER,
        JUG INTEGER,
        KIND INTEGER,
        UEBTR_DATUM TIMESTAMP DEFAULT current_timestamp

,
        TA_STATUS INTEGER,
        BK_LNR INTEGER,
        PRL_LNR INTEGER,
        ISROOM INTEGER,
PRIMARY KEY (LNR));
SET TERM ^ ;

/* Triggers only will work for SQL triggers */
CREATE TRIGGER FM_PROT_BI FOR FM_PROT 
ACTIVE BEFORE INSERT POSITION 0 
AS
BEGIN
  IF (NEW.LNR IS NULL) THEN
    NEW.LNR = GEN_ID(GEN_FM_PROT_ID,1);
END ^

CREATE TRIGGER FREIMELD_PREISLIST_BI FOR FREIMELD_PREISLIST 
ACTIVE BEFORE INSERT POSITION 0 
AS
BEGIN
  IF (NEW.LNR IS NULL) THEN
    NEW.LNR = GEN_ID(GEN_FREIMELD_PREISLIST_ID,1);
END ^

CREATE TRIGGER FREIMELD_VAKANZ_BI FOR FREIMELD_VAKANZ 
ACTIVE BEFORE INSERT POSITION 0 
AS
BEGIN
  IF (NEW.LNR IS NULL) THEN
    NEW.LNR = GEN_ID(GEN_FREIMELD_VAKANZ_ID,1);
END ^

CREATE TRIGGER FREIMELD_VAKANZ_AI99 FOR FREIMELD_VAKANZ 
ACTIVE AFTER INSERT POSITION 99 
AS
begin
  /* Trigger text */
  delete from freimeld_vakanz
where cast (UEBTR_DATUM as date) < current_date -12;
end ^

CREATE TRIGGER HIS_PROT_BI FOR HIS_PROT 
ACTIVE BEFORE INSERT POSITION 0 
AS
BEGIN
  IF (NEW.LNR IS NULL) THEN
    NEW.LNR = GEN_ID(GEN_HIS_PROT_ID,1);
END ^

CREATE TRIGGER TEMP_RATEBOARD_BI FOR TEMP_RATEBOARD 
ACTIVE BEFORE INSERT POSITION 0 
AS
BEGIN
  IF (NEW.LNR IS NULL) THEN
    NEW.LNR = GEN_ID(GEN_TEMP_RATEBOARD_ID,1);
END ^


SET TERM ; ^
COMMIT WORK;

/* Grant permissions for this database */
GRANT DELETE, INSERT, SELECT, UPDATE, REFERENCES ON FREIMELD_PREISLIST TO USER CDS;
GRANT USAGE ON SEQUENCE GEN_FM_PROT_ID TO PUBLIC;
GRANT USAGE ON SEQUENCE GEN_FREIMELD_VAKANZ_ID TO PUBLIC;
GRANT USAGE ON SEQUENCE GEN_HIS_PROT_ID TO PUBLIC;
GRANT USAGE ON SEQUENCE GEN_TEMP_RATEBOARD_ID TO PUBLIC;
