-- entity: addresses
-- source: ADRESSEN
-- columns: lnr:int, adr_wahl:int, anrede:text, titel:text, name1:text, name2:text, namenzus:text, strasse:text, landkenn:text, land:text, plz:text, ort:text, sprache:int, tele1:text, tele2:text, tele3:text, e_mail:text, gebdat:date, geschlecht:text, id_nr:text, id_nr_ausgestellt:text, st_angeh:text, kfz_kennz:text, newsletter:bool, suchname:text, matchcode:text, gastnr:int, debi_nr:int, steuernummer:text, pr_code:int, rabatt:amount, prov_proz:amount, logi_ok:bool, kurt_ok:bool, logi_betrag:amount, wunsch_zi:text, begleit:text, begleit_v:text, begleit_g:date, b_strasse:text, b_land:text, b_plz:text, b_ort:text, id_nr_begl:text, k1:text, k1_nname:text, k1_geb:date, id_nr_k1:text, k2:text, k2_nname:text, k2_geb:date, id_nr_k2:text, k3:text, k3_nname:text, k3_geb:date, id_nr_k3:text, k4:text, k4_nname:text, k4_geb:date, id_nr_k4:text, k5:text, k5_nname:text, k5_geb:date, id_nr_k5:text, bemerk:blob, bemerk2:text, ds_vorgenommen:int, ds_version:int, erf_datum:date, kor_datum:date
--
-- Дельта (задача 8 §3): лише рядки броней, що заїжджають або виїжджають у вікні {{FROM}}..{{TO}}
-- (або живуть у ньому наскрізь). Агент підставляє дати замість {{FROM}}/{{TO}}.
-- Рядок `-- columns:` МУСИТЬ збігатися з apps/winhotel-import/sql/<сутність>.sql: міст розбирає вивід за ним.
SET HEADING OFF;
SELECT
     COALESCE(CAST(LNR AS VARCHAR(30)), '') || ASCII_CHAR(31)
  || COALESCE(CAST(ADR_WAHL AS VARCHAR(30)), '') || ASCII_CHAR(31)
  || COALESCE(ANREDE, '') || ASCII_CHAR(31)
  || COALESCE(TITEL, '') || ASCII_CHAR(31)
  || COALESCE(NAME1, '') || ASCII_CHAR(31)
  || COALESCE(NAME2, '') || ASCII_CHAR(31)
  || COALESCE(NAMENZUS, '') || ASCII_CHAR(31)
  || COALESCE(STRASSE, '') || ASCII_CHAR(31)
  || COALESCE(LANDKENN, '') || ASCII_CHAR(31)
  || COALESCE(LAND, '') || ASCII_CHAR(31)
  || COALESCE(PLZ, '') || ASCII_CHAR(31)
  || COALESCE(ORT, '') || ASCII_CHAR(31)
  || COALESCE(CAST(SPRACHE AS VARCHAR(30)), '') || ASCII_CHAR(31)
  || COALESCE(TELE1, '') || ASCII_CHAR(31)
  || COALESCE(TELE2, '') || ASCII_CHAR(31)
  || COALESCE(TELE3, '') || ASCII_CHAR(31)
  || COALESCE(E_MAIL, '') || ASCII_CHAR(31)
  || COALESCE(CAST(GEBDAT AS VARCHAR(10)), '') || ASCII_CHAR(31)
  || COALESCE(GESCHLECHT, '') || ASCII_CHAR(31)
  || COALESCE(ID_NR, '') || ASCII_CHAR(31)
  || COALESCE(ID_NR_AUSGESTELLT, '') || ASCII_CHAR(31)
  || COALESCE(ST_ANGEH, '') || ASCII_CHAR(31)
  || COALESCE(KFZ_KENNZ, '') || ASCII_CHAR(31)
  || COALESCE(CAST(NEWSLETTER AS VARCHAR(30)), '') || ASCII_CHAR(31)
  || COALESCE(SUCHNAME, '') || ASCII_CHAR(31)
  || COALESCE(MATCHCODE, '') || ASCII_CHAR(31)
  || COALESCE(CAST(GASTNR AS VARCHAR(30)), '') || ASCII_CHAR(31)
  || COALESCE(CAST(DEBI_NR AS VARCHAR(30)), '') || ASCII_CHAR(31)
  || COALESCE(STEUERNUMMER, '') || ASCII_CHAR(31)
  || COALESCE(CAST(PR_CODE AS VARCHAR(30)), '') || ASCII_CHAR(31)
  || COALESCE(CAST(RABATT AS VARCHAR(30)), '') || ASCII_CHAR(31)
  || COALESCE(CAST(PROV_PROZ AS VARCHAR(30)), '') || ASCII_CHAR(31)
  || COALESCE(CAST(LOGI_OK AS VARCHAR(30)), '') || ASCII_CHAR(31)
  || COALESCE(CAST(KURT_OK AS VARCHAR(30)), '') || ASCII_CHAR(31)
  || COALESCE(CAST(LOGI_BETRAG AS VARCHAR(30)), '') || ASCII_CHAR(31)
  || COALESCE(WUNSCH_ZI, '') || ASCII_CHAR(31)
  || COALESCE(BEGLEIT, '') || ASCII_CHAR(31)
  || COALESCE(BEGLEIT_V, '') || ASCII_CHAR(31)
  || COALESCE(CAST(BEGLEIT_G AS VARCHAR(10)), '') || ASCII_CHAR(31)
  || COALESCE(B_STRASSE, '') || ASCII_CHAR(31)
  || COALESCE(B_LAND, '') || ASCII_CHAR(31)
  || COALESCE(B_PLZ, '') || ASCII_CHAR(31)
  || COALESCE(B_ORT, '') || ASCII_CHAR(31)
  || COALESCE(ID_NR_BEGL, '') || ASCII_CHAR(31)
  || COALESCE(K1, '') || ASCII_CHAR(31)
  || COALESCE(K1_NNAME, '') || ASCII_CHAR(31)
  || COALESCE(CAST(K1_GEB AS VARCHAR(10)), '') || ASCII_CHAR(31)
  || COALESCE(ID_NR_K1, '') || ASCII_CHAR(31)
  || COALESCE(K2, '') || ASCII_CHAR(31)
  || COALESCE(K2_NNAME, '') || ASCII_CHAR(31)
  || COALESCE(CAST(K2_GEB AS VARCHAR(10)), '') || ASCII_CHAR(31)
  || COALESCE(ID_NR_K2, '') || ASCII_CHAR(31)
  || COALESCE(K3, '') || ASCII_CHAR(31)
  || COALESCE(K3_NNAME, '') || ASCII_CHAR(31)
  || COALESCE(CAST(K3_GEB AS VARCHAR(10)), '') || ASCII_CHAR(31)
  || COALESCE(ID_NR_K3, '') || ASCII_CHAR(31)
  || COALESCE(K4, '') || ASCII_CHAR(31)
  || COALESCE(K4_NNAME, '') || ASCII_CHAR(31)
  || COALESCE(CAST(K4_GEB AS VARCHAR(10)), '') || ASCII_CHAR(31)
  || COALESCE(ID_NR_K4, '') || ASCII_CHAR(31)
  || COALESCE(K5, '') || ASCII_CHAR(31)
  || COALESCE(K5_NNAME, '') || ASCII_CHAR(31)
  || COALESCE(CAST(K5_GEB AS VARCHAR(10)), '') || ASCII_CHAR(31)
  || COALESCE(ID_NR_K5, '') || ASCII_CHAR(31)
  || COALESCE(CAST(SUBSTRING(BEMERK FROM 1 FOR 2000) AS VARCHAR(2000)), '') || ASCII_CHAR(31)
  || COALESCE(BEMERK2, '') || ASCII_CHAR(31)
  || COALESCE(CAST(DS_VORGENOMMEN AS VARCHAR(30)), '') || ASCII_CHAR(31)
  || COALESCE(CAST(DS_VERSION AS VARCHAR(30)), '') || ASCII_CHAR(31)
  || COALESCE(CAST(ERF_DATUM AS VARCHAR(10)), '') || ASCII_CHAR(31)
  || COALESCE(CAST(KOR_DATUM AS VARCHAR(10)), '') || ASCII_CHAR(30)
FROM ADRESSEN
WHERE TA_STATUS < 1000 AND LNR IN (SELECT GASTNR_1 FROM GASTKONT WHERE (VONAUFH BETWEEN '{{FROM}}' AND '{{TO}}' OR BISAUFH BETWEEN '{{FROM}}' AND '{{TO}}' OR (VONAUFH < '{{FROM}}' AND BISAUFH > '{{TO}}')) UNION SELECT GASTNR_2 FROM GASTKONT WHERE (VONAUFH BETWEEN '{{FROM}}' AND '{{TO}}' OR BISAUFH BETWEEN '{{FROM}}' AND '{{TO}}' OR (VONAUFH < '{{FROM}}' AND BISAUFH > '{{TO}}')) UNION SELECT GASTNR_3 FROM GASTKONT WHERE (VONAUFH BETWEEN '{{FROM}}' AND '{{TO}}' OR BISAUFH BETWEEN '{{FROM}}' AND '{{TO}}' OR (VONAUFH < '{{FROM}}' AND BISAUFH > '{{TO}}')));
