/**
 * SQL that only SQLite understands.
 *
 *   node scripts/check-dialect.mjs            # report
 *   node scripts/check-dialect.mjs --strict   # exit 1 if anything is left
 *
 * The seam made the call SHAPE portable — four methods, `?` placeholders, and
 * a Postgres implementation that satisfies the same contract. It did not make
 * the SQL portable, and that is a separate, larger job: `datetime('now')`,
 * `strftime`, `INSERT OR IGNORE`, `rowid` and friends are SQLite spellings that
 * Postgres rejects outright.
 *
 * Rejects outright is the good case. The dangerous ones are the constructs both
 * accept with DIFFERENT meaning — those are listed here too, and marked.
 *
 * The count reached zero, so --strict is now part of `npm run check`. Anything
 * that puts a SQLite-only spelling back fails the build rather than waiting to
 * be discovered the day someone sets DB_DRIVER=postgres.
 */
import fs from 'node:fs';
import path from 'node:path';

// Application code only. src/lib/db.ts is deliberately NOT here: it is the
// SQLite bootstrap — the schema and its migrations — and on Postgres it is
// replaced wholesale by db/postgres/schema.sql rather than translated. It is
// full of PRAGMA, AUTOINCREMENT and datetime('now') and always will be.
const ROOTS = ['src/modules', 'src/core', 'src/app/api'];

/**
 * Each rule: what to look for, what Postgres wants instead, and whether the
 * difference is loud (a syntax error) or quiet (both run, results differ).
 */
const RULES = [
  { id: 'datetime-now', re: /datetime\('now'\)/g, quiet: false,
    fix: "CURRENT_TIMESTAMP — SQLite accepts it too, so this one is a safe swap" },
  { id: 'date-now', re: /date\('now'[^)]*\)/g, quiet: false,
    fix: "compute the date in JavaScript and pass it as a parameter" },
  { id: 'strftime', re: /strftime\(/g, quiet: false,
    fix: "to_char(col, 'YYYY-MM') on Postgres — no shared spelling, needs a branch or a computed column" },
  { id: 'julianday', re: /julianday\(/g, quiet: false,
    fix: 'subtract dates directly; Postgres returns an interval' },
  { id: 'insert-or-ignore', re: /INSERT\s+OR\s+IGNORE/gi, quiet: false,
    fix: 'INSERT ... ON CONFLICT DO NOTHING — SQLite has supported it since 3.24, so a safe swap' },
  { id: 'insert-or-replace', re: /INSERT\s+OR\s+REPLACE/gi, quiet: false,
    fix: 'INSERT ... ON CONFLICT (key) DO UPDATE SET ... — the columns have to be named' },
  // `col IS ?` is SQLite's null-safe comparison. Postgres accepts only NULL,
  // TRUE, FALSE, UNKNOWN or DISTINCT FROM after IS, so a parameter there does
  // not even parse: "syntax error at or near $4". Four places had it, and each
  // was the lookup that decides insert-or-update — so saving a budget, a
  // category, a project or a counterparty failed outright.
  { id: 'is-placeholder', re: /\bIS\s+\?/gi, quiet: false,
    fix: 'col IS NOT DISTINCT FROM ? — standard, null-safe, and both engines accept it' },
  // Inside DO UPDATE SET, a bare column on the right-hand side is ambiguous in
  // Postgres between the target row and `excluded`. SQLite picks the target and
  // says nothing. This one numbered every invoice.
  { id: 'conflict-bare-column', re: /DO\s+UPDATE\s+SET\s+(\w+)\s*=\s*\1\b/gi, quiet: false,
    fix: 'qualify it: DO UPDATE SET n = <table>.n + 1' },
  // Case-sensitive on purpose: `rowId` is a perfectly ordinary variable name,
  // and 34 of them live in one P&L mapping function.
  { id: 'rowid', re: /\browid\b/g, quiet: false,
    fix: 'RETURNING id, read from the row — Postgres has no rowid' },
  { id: 'randomblob', re: /randomblob\(/g, quiet: false,
    fix: 'gen_random_uuid() on Postgres, or generate the id in JavaScript for both' },
  // Eight handlers asked this before using a table, and Postgres has no such
  // relation — the query did not answer "no", it threw and took the request
  // with it. `sql.dialect.tables()` names the catalogue per engine.
  { id: 'sqlite-catalogue', re: /sqlite_master|sqlite_version\(/gi, quiet: false,
    fix: 'use sql.dialect.tables() — pg_tables on Postgres, sqlite_master on SQLite' },
  // Schema changes from a request handler. Every one of these was written
  // against SQLite, where a process that opens the file may alter it; the
  // application's Postgres role owns nothing and may not. Three of them —
  // an index on every Hostex sync, a table on every handshake, a column on
  // every service order — each took a route down on the first real run.
  { id: 'runtime-ddl', re: /(CREATE\s+(TABLE|INDEX)|ALTER\s+TABLE|DROP\s+(TABLE|INDEX))/gi, quiet: false,
    fix: 'schema belongs in the boot migration and in db/postgres/schema.sql, not in a handler' },
  { id: 'pragma', re: /PRAGMA\s+\w+/gi, quiet: false,
    fix: 'information_schema on Postgres — these are schema introspection, mostly in migrations' },
  { id: 'autoincrement', re: /AUTOINCREMENT/gi, quiet: false,
    fix: 'GENERATED BY DEFAULT AS IDENTITY (the generated schema already does this)' },
  // Quiet ones: both engines run these, and disagree.
  { id: 'concat-plus', re: /\|\|\s*['"]/g, quiet: true,
    fix: "both concatenate, but SQLite turns NULL||'x' into NULL and so does Postgres — same here, listed only to be checked once" },
];

/**
 * A boolean column compared to 0 or 1.
 *
 * SQLite has no boolean type — a flag is the integer 1 — so `WHERE is_active =
 * 1` is the ordinary spelling and appears in this codebase 100-odd times.
 * Postgres refuses it outright: `operator does not exist: boolean = integer`.
 *
 * There was a rule here before, matching any `= 1`, marked quiet, explaining
 * that "the generated schema keeps these INTEGER, so this is informational".
 * That stopped being true when the generator started emitting BOOLEAN — 27
 * columns now — and nothing revisited the note. So the check reported zero
 * loud problems while the very first tenant to create a property on Postgres
 * got a 500.
 *
 * Which columns are boolean is not guessed: it is read from the generated
 * schema, the same file the database is created from. That makes the rule
 * precise enough to be loud, and it cannot drift from the schema.
 */
const BOOLEAN_COLUMNS = [...new Set(
  [...fs.readFileSync('db/postgres/schema.sql', 'utf8')
    .matchAll(/^\s+"([a-z0-9_]+)"\s+BOOLEAN\b/gm)].map((m) => m[1]),
)];
if (BOOLEAN_COLUMNS.length) {
  RULES.push({
    id: 'boolean-int',
    // Two shapes, and the second was missed for a month because what sits
    // before the `=` is a closing parenthesis rather than a column name:
    //   is_active = 1
    //   COALESCE(is_capex, 0)      — Postgres refuses to mix the two types
    re: new RegExp(
      `\\b(?:${BOOLEAN_COLUMNS.join('|')})\\s*(?:=|!=|<>)\\s*[01]\\b`
      + `|COALESCE\\(\\s*(?:[a-z_]+\\.)?(?:${BOOLEAN_COLUMNS.join('|')})\\s*,\\s*[01]\\s*\\)`,
      'gi',
    ),
    quiet: false,
    fix: 'compare a BOOLEAN to TRUE/FALSE, not to 1/0 — both engines accept that spelling',
  });
}

const files = [];
function walk(dir) {
  if (!fs.existsSync(dir)) return;
  for (const e of fs.readdirSync(dir, { withFileTypes: true })) {
    const full = path.join(dir, e.name);
    if (e.isDirectory()) walk(full);
    // The two Sql implementations are where the SQLite and Postgres spellings
    // legitimately live — counting them would mean the check can never reach
    // zero, and a target that cannot be reached is not a target.
    else if (/\.tsx?$/.test(e.name) && !e.name.endsWith('.check.ts')
             && !/db[\\/](async|postgres)\.ts$/.test(full)) files.push(full);
  }
}
for (const r of ROOTS) walk(r);

/**
 * Everything that is not inside a string literal, blanked out.
 *
 * SQL lives in string literals; TypeScript does not. Scanning raw lines meant
 * `const { is_default = 0 } = body` — a destructuring default — counted as a
 * boolean compared to an integer, and a rule that fires on code is a rule
 * people learn to ignore. Skipping lines that START with // caught some of it
 * and nothing else: not a trailing comment, not an identifier, not a JSDoc
 * line without a leading star.
 *
 * Positions are preserved rather than removed, so line numbers stay honest.
 * Most SQL here is a multi-line template, which is why this cannot be done a
 * line at a time.
 */
function sqlOnly(src) {
  const out = new Array(src.length).fill(' ');
  let i = 0, quote = null;
  while (i < src.length) {
    const c = src[i];
    if (src[i] === '\n') { out[i] = '\n'; i++; continue; }
    if (quote === null) {
      if (src.startsWith('//', i)) { while (i < src.length && src[i] !== '\n') i++; continue; }
      if (src.startsWith('/*', i)) {
        const end = src.indexOf('*/', i);
        const stop = end < 0 ? src.length : end + 2;
        for (; i < stop; i++) if (src[i] === '\n') out[i] = '\n';
        continue;
      }
      if (c === "'" || c === '"' || c === '`') quote = c;
      i++;
      continue;
    }
    if (c === '\\') { i += 2; continue; }
    if (c === quote) { quote = null; i++; continue; }
    out[i] = c;
    i++;
  }
  return out.join('');
}

const found = new Map(RULES.map((r) => [r.id, []]));

for (const f of files) {
  const src = fs.readFileSync(f, 'utf8');
  const real = src.split('\n');
  sqlOnly(src).split('\n').forEach((line, i) => {
    for (const rule of RULES) {
      rule.re.lastIndex = 0;
      if (rule.re.test(line)) {
        found.get(rule.id).push({ file: f, line: i + 1, text: real[i].trim().slice(0, 90) });
      }
    }
  });
}

const loud = RULES.filter((r) => !r.quiet);
const quiet = RULES.filter((r) => r.quiet);
const loudTotal = loud.reduce((n, r) => n + found.get(r.id).length, 0);

console.log('\nдіалект: SQL, який Postgres не зрозуміє\n');
for (const rule of loud) {
  const hits = found.get(rule.id);
  if (!hits.length) continue;
  console.log(`  ${rule.id.padEnd(20)} ${String(hits.length).padStart(4)}   → ${rule.fix}`);
  const byFile = new Map();
  for (const h of hits) byFile.set(h.file, (byFile.get(h.file) || 0) + 1);
  const top = [...byFile.entries()].sort((a, b) => b[1] - a[1]).slice(0, 3);
  console.log(`  ${' '.repeat(20)}      ${top.map(([f, n]) => `${f.replace(/\\/g, '/')} (${n})`).join(', ')}`);
  // A count and a filename are enough to know there is work; they are not
  // enough to do it. --list prints where.
  if (process.argv.includes('--list')) {
    for (const h of hits) console.log(`      ${h.file.replace(/\\/g, '/')}:${h.line}  ${h.text}`);
  }
  console.log();
}

console.log(`  разом гучних (синтаксична помилка на Postgres): ${loudTotal}`);
console.log('  перевірено: src/modules, src/core, src/app/api — код застосунку.');
console.log('  НЕ перевірено: src/lib/db.ts — це створення схеми SQLite, яке на');
console.log('  Postgres заміняє db/postgres/schema.sql, а не переклад.');
const quietTotal = quiet.reduce((n, r) => n + found.get(r.id).length, 0);
console.log(`  тихих (обидва виконають, результат може різнитись): ${quietTotal} — переглянути раз, не блокує\n`);

if (process.argv.includes('--strict') && loudTotal > 0) process.exit(1);
