/**
 * SQL that only SQLite understands.
 *
 *   node scripts/check-dialect.mjs            # report
 *   node scripts/check-dialect.mjs --strict   # exit 1 if anything is left
 *
 * The seam made the call SHAPE portable — four methods, `?` placeholders, and
 * a Postgres implementation that satisfies the same contract. It did not make
 * the SQL portable, and that is a separate, larger job: `datetime('now')`,
 * `strftime`, `INSERT OR IGNORE`, `rowid` and friends are SQLite spellings that
 * Postgres rejects outright.
 *
 * Rejects outright is the good case. The dangerous ones are the constructs both
 * accept with DIFFERENT meaning — those are listed here too, and marked.
 *
 * The count reached zero, so --strict is now part of `npm run check`. Anything
 * that puts a SQLite-only spelling back fails the build rather than waiting to
 * be discovered the day someone sets DB_DRIVER=postgres.
 */
import fs from 'node:fs';
import path from 'node:path';

const ROOTS = ['src/modules', 'src/core', 'src/app/api'];

/**
 * Each rule: what to look for, what Postgres wants instead, and whether the
 * difference is loud (a syntax error) or quiet (both run, results differ).
 */
const RULES = [
  { id: 'datetime-now', re: /datetime\('now'\)/g, quiet: false,
    fix: "CURRENT_TIMESTAMP — SQLite accepts it too, so this one is a safe swap" },
  { id: 'date-now', re: /date\('now'[^)]*\)/g, quiet: false,
    fix: "compute the date in JavaScript and pass it as a parameter" },
  { id: 'strftime', re: /strftime\(/g, quiet: false,
    fix: "to_char(col, 'YYYY-MM') on Postgres — no shared spelling, needs a branch or a computed column" },
  { id: 'julianday', re: /julianday\(/g, quiet: false,
    fix: 'subtract dates directly; Postgres returns an interval' },
  { id: 'insert-or-ignore', re: /INSERT\s+OR\s+IGNORE/gi, quiet: false,
    fix: 'INSERT ... ON CONFLICT DO NOTHING — SQLite has supported it since 3.24, so a safe swap' },
  { id: 'insert-or-replace', re: /INSERT\s+OR\s+REPLACE/gi, quiet: false,
    fix: 'INSERT ... ON CONFLICT (key) DO UPDATE SET ... — the columns have to be named' },
  // Case-sensitive on purpose: `rowId` is a perfectly ordinary variable name,
  // and 34 of them live in one P&L mapping function.
  { id: 'rowid', re: /\browid\b/g, quiet: false,
    fix: 'RETURNING id, read from the row — Postgres has no rowid' },
  { id: 'randomblob', re: /randomblob\(/g, quiet: false,
    fix: 'gen_random_uuid() on Postgres, or generate the id in JavaScript for both' },
  { id: 'pragma', re: /PRAGMA\s+\w+/gi, quiet: false,
    fix: 'information_schema on Postgres — these are schema introspection, mostly in migrations' },
  { id: 'autoincrement', re: /AUTOINCREMENT/gi, quiet: false,
    fix: 'GENERATED BY DEFAULT AS IDENTITY (the generated schema already does this)' },
  // Quiet ones: both engines run these, and disagree.
  { id: 'concat-plus', re: /\|\|\s*['"]/g, quiet: true,
    fix: "both concatenate, but SQLite turns NULL||'x' into NULL and so does Postgres — same here, listed only to be checked once" },
  { id: 'boolean-int', re: /=\s*1\s*(?:AND|OR|\)|$)/gm, quiet: true,
    fix: 'a BOOLEAN column compared to 1 is a type error on Postgres; the generated schema keeps these INTEGER, so this is informational' },
];

const files = [];
function walk(dir) {
  if (!fs.existsSync(dir)) return;
  for (const e of fs.readdirSync(dir, { withFileTypes: true })) {
    const full = path.join(dir, e.name);
    if (e.isDirectory()) walk(full);
    // The two Sql implementations are where the SQLite and Postgres spellings
    // legitimately live — counting them would mean the check can never reach
    // zero, and a target that cannot be reached is not a target.
    else if (/\.tsx?$/.test(e.name) && !e.name.endsWith('.check.ts')
             && !/db[\\/](async|postgres)\.ts$/.test(full)) files.push(full);
  }
}
for (const r of ROOTS) walk(r);

const found = new Map(RULES.map((r) => [r.id, []]));

for (const f of files) {
  const src = fs.readFileSync(f, 'utf8');
  const lines = src.split('\n');
  lines.forEach((line, i) => {
    const t = line.trim();
    if (t.startsWith('//') || t.startsWith('*')) return;
    for (const rule of RULES) {
      rule.re.lastIndex = 0;
      if (rule.re.test(line)) found.get(rule.id).push({ file: f, line: i + 1, text: t.slice(0, 90) });
    }
  });
}

const loud = RULES.filter((r) => !r.quiet);
const quiet = RULES.filter((r) => r.quiet);
const loudTotal = loud.reduce((n, r) => n + found.get(r.id).length, 0);

console.log('\nдіалект: SQL, який Postgres не зрозуміє\n');
for (const rule of loud) {
  const hits = found.get(rule.id);
  if (!hits.length) continue;
  console.log(`  ${rule.id.padEnd(20)} ${String(hits.length).padStart(4)}   → ${rule.fix}`);
  const byFile = new Map();
  for (const h of hits) byFile.set(h.file, (byFile.get(h.file) || 0) + 1);
  const top = [...byFile.entries()].sort((a, b) => b[1] - a[1]).slice(0, 3);
  console.log(`  ${' '.repeat(20)}      ${top.map(([f, n]) => `${f.replace(/\\/g, '/')} (${n})`).join(', ')}`);
  console.log();
}

console.log(`  разом гучних (синтаксична помилка на Postgres): ${loudTotal}`);
const quietTotal = quiet.reduce((n, r) => n + found.get(r.id).length, 0);
console.log(`  тихих (обидва виконають, результат може різнитись): ${quietTotal} — переглянути раз, не блокує\n`);

if (process.argv.includes('--strict') && loudTotal > 0) process.exit(1);
