-- Five tables let SQLite assign their primary key, and Postgres would not.
--
-- `id INTEGER PRIMARY KEY` in SQLite is the rowid alias: omit it on INSERT and
-- SQLite fills it in. The generated Postgres schema carried the type and the
-- NOT NULL across but nothing that produces a value, so the first INSERT that
-- relied on it failed:
--
--   null value in column "id" of relation "hostex_sync_log" violates not-null
--
-- which is how the Hostex sync died on beta's first run against Postgres.
--
-- BY DEFAULT rather than ALWAYS, because pg-import writes the ids it is
-- copying. It resets each sequence past the highest imported id afterwards.
--
-- db/postgres/schema.sql now generates this (see rowidAlias in
-- scripts/pg-schema.mjs), so a database created from it needs nothing here.
-- This is for one created before. Re-runnable.

BEGIN;

DO $$
DECLARE target record;
BEGIN
  FOR target IN
    SELECT t.name, t.col
    FROM (VALUES
      ('hostex_sync_log',      'id'),
      ('hostex_property_map',  'hostex_property_id'),
      ('content_translations', 'id'),
      ('fin_auto_rule_matches','id'),
      ('tg_booking_messages',  'id')
    ) AS t(name, col)
    JOIN information_schema.columns c
      ON c.table_schema = 'public' AND c.table_name = t.name AND c.column_name = t.col
    WHERE c.is_identity = 'NO'
  LOOP
    EXECUTE format('ALTER TABLE %I ALTER COLUMN %I ADD GENERATED BY DEFAULT AS IDENTITY',
                   target.name, target.col);
    RAISE NOTICE 'identity added: %.%', target.name, target.col;
  END LOOP;
END $$;

COMMIT;
